export const MENU_IDS = {
    PRINCIPAL: {
        OPCION1: "MENU_PRINCIPAL_OPCION1",
        OPCION2: "MENU_PRINCIPAL_OPCION2",
        OPCION3: "MENU_PRINCIPAL_OPCION3",
    },
    SUBMENU_1: {
        OPCION1: "SUBMENU1_OPCION1",
        OPCION2: "SUBMENU1_OPCION2",
    },
    SUBMENU_2: {
        OPCION1: "SUBMENU2_OPCION1",
        OPCION2: "SUBMENU2_OPCION2",
    },
    SUBMENU_3: {
        OPCION1: "SUBMENU3_OPCION1",
        OPCION2: "SUBMENU3_OPCION2",
        OPCION3: "SUBMENU3_OPCION3",
    }
};